title: "Emmanuel Stone2"
show_downloads: false
#theme: jekyll-theme-minimal
remote_theme: jekyll/minima
github:
  is_user_page: false
  is_project_page: false
minima:
  skin: classic
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
